// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBPyyk99nT568HYKKhhMVK-9x1vD1W30EU',
    appId: '1:851830409444:web:119a1731f42682883284f1',
    messagingSenderId: '851830409444',
    projectId: 'sohbet-f963a',
    authDomain: 'sohbet-f963a.firebaseapp.com',
    storageBucket: 'sohbet-f963a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCATibS2uuJT_wksGLlfqp_pg_u_OEaMUU',
    appId: '1:851830409444:android:496da7d3b62d03793284f1',
    messagingSenderId: '851830409444',
    projectId: 'sohbet-f963a',
    storageBucket: 'sohbet-f963a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCNj9duP6OJbc1rB6csYgjsgmNUnUfox5k',
    appId: '1:851830409444:ios:10a58fd0fa6720c93284f1',
    messagingSenderId: '851830409444',
    projectId: 'sohbet-f963a',
    storageBucket: 'sohbet-f963a.appspot.com',
    iosBundleId: 'com.example.chat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCNj9duP6OJbc1rB6csYgjsgmNUnUfox5k',
    appId: '1:851830409444:ios:10a58fd0fa6720c93284f1',
    messagingSenderId: '851830409444',
    projectId: 'sohbet-f963a',
    storageBucket: 'sohbet-f963a.appspot.com',
    iosBundleId: 'com.example.chat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBPyyk99nT568HYKKhhMVK-9x1vD1W30EU',
    appId: '1:851830409444:web:08d4be87191d220f3284f1',
    messagingSenderId: '851830409444',
    projectId: 'sohbet-f963a',
    authDomain: 'sohbet-f963a.firebaseapp.com',
    storageBucket: 'sohbet-f963a.appspot.com',
  );
}
